_wandb:
    value:
        cli_version: 0.23.1
        e:
            nqghztil39unkul47kj7ippmgv05908b:
                args:
                    - --alpha
                    - "0.3"
                codePath: train_grassy.py
                codePathLocal: train_grassy.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "109951162777600"
                        used: "76720155131904"
                email: stolkowsky@gmail.com
                executable: /sci/labs/orzuk/shaulytolk/GRASSY-Net/molenv/bin/python
                git:
                    commit: 4fbcbda4a48c48c695144f643c8c3a19c490fdaa
                    remote: https://github.com/KrishnaswamyLab/GRASSY-Net.git
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-fa32ddd6-e341-1579-8eee-fdd42052b558
                host: salmon-01
                memory:
                    total: "1623069495296"
                os: Linux-6.12.32-aufs-1-x86_64-with-glibc2.36
                program: /sci/labs/orzuk/shaulytolk/GRASSY-Net/train_grassy.py
                python: CPython 3.11.2
                root: scripts/final_logs/ZINC12K_regress_nokld_2026-01-05-15-15-11/
                slurm:
                    cluster_name: moriah
                    conf: /vol/slurm/moriah/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gtids: "0"
                    job_account: orzuk
                    job_cpus_per_node: "4"
                    job_gid: "925"
                    job_gpus: "3"
                    job_id: "43607859"
                    job_name: grassy_alpha03
                    job_nodelist: salmon-01
                    job_num_nodes: "1"
                    job_partition: salmon
                    job_qos: normal
                    job_uid: "212767"
                    job_user: shaulytolk
                    jobid: "43607859"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: salmon-01
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /sci/labs/orzuk/shaulytolk/GRASSY-Net
                    submit_host: moriah-gw-02
                    task_pid: "1008838"
                    tasks_per_node: "1"
                    topology_addr: salmon-01
                    topology_addr_pattern: node
                    working_cluster: moriah:slurmctl-01:6840:9216:109
                startedAt: "2026-01-05T13:15:13.364177Z"
                writerId: nqghztil39unkul47kj7ippmgv05908b
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 9
                - 51
                - 77
                - 103
            "2":
                - 1
                - 9
                - 51
                - 77
                - 103
            "3":
                - 3
                - 7
                - 13
                - 66
            "4": 3.11.2
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
GRASSY_version:
    value: AE+REG
accelerator:
    value: null
accumulate_grad_batches:
    value: null
alpha:
    value: 0.3
auto_select_gpus:
    value: null
batch_size:
    value: 100
beta:
    value: 0
bottle_dim:
    value: 25
check_val_every_n_epoch:
    value: 1
default_root_dir:
    value: null
devices:
    value: null
enable_checkpointing:
    value: true
enable_model_summary:
    value: true
enable_progress_bar:
    value: true
fast_dev_run:
    value: false
gpus:
    value: null
gradient_clip_algorithm:
    value: null
gradient_clip_val:
    value: null
hidden_dim:
    value: 100
input_dim:
    value: 704
ipus:
    value: null
learning_rate:
    value: 0.001
len_epoch:
    value: 100
limit_predict_batches:
    value: null
limit_test_batches:
    value: null
limit_train_batches:
    value: null
limit_val_batches:
    value: null
log_every_n_steps:
    value: 50
logger:
    value: true
max_epochs:
    value: null
max_steps:
    value: -1
max_time:
    value: null
min_epochs:
    value: null
min_steps:
    value: null
n_epochs:
    value: 100
n_gpus:
    value: 1
num_nodes:
    value: 1
num_processes:
    value: null
num_properties:
    value: 13
num_sanity_val_steps:
    value: 2
overfit_batches:
    value: 0
precision:
    value: 32
resume_from_checkpoint:
    value: null
save_dir:
    value: scripts/final_logs/
strategy:
    value: null
sync_batchnorm:
    value: false
tpu_cores:
    value: null
track_grad_norm:
    value: -1
val_check_interval:
    value: null
