_wandb:
    value:
        cli_version: 0.23.1
        e:
            9pgimkwo8l6qs2vturi5pyu87tzpyspa:
                args:
                    - --alpha
                    - "0.1"
                codePath: train_grassy.py
                codePathLocal: train_grassy.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "109951162777600"
                        used: "76395225022464"
                email: stolkowsky@gmail.com
                executable: /sci/labs/orzuk/shaulytolk/GRASSY-Net/molenv/bin/python
                git:
                    commit: a8ca629743ef236eed40cafc2cc5c31aa68c57b0
                    remote: https://github.com/KrishnaswamyLab/GRASSY-Net.git
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-65efbacf-5e71-d8ac-a761-788adc6a3deb
                host: salmon-08
                memory:
                    total: "1623069478912"
                os: Linux-6.12.32-aufs-1-x86_64-with-glibc2.36
                program: /sci/labs/orzuk/shaulytolk/GRASSY-Net/train_grassy.py
                python: CPython 3.11.2
                root: scripts/final_logs/ZINC12K_regress_nokld/
                slurm:
                    cluster_name: moriah
                    conf: /vol/slurm/moriah/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gtids: "0"
                    job_account: orzuk
                    job_cpus_per_node: "4"
                    job_gid: "925"
                    job_gpus: "0"
                    job_id: "43550499"
                    job_name: grassy_a01
                    job_nodelist: salmon-08
                    job_num_nodes: "1"
                    job_partition: salmon
                    job_qos: normal
                    job_uid: "212767"
                    job_user: shaulytolk
                    jobid: "43550499"
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: salmon-08
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /sci/labs/orzuk/shaulytolk/GRASSY-Net
                    submit_host: moriah-gw-02
                    task_pid: "2189972"
                    tasks_per_node: "1"
                    topology_addr: salmon-08
                    topology_addr_pattern: node
                    working_cluster: moriah:slurmctl-01:6840:9216:109
                startedAt: "2025-12-29T18:50:44.071274Z"
                writerId: 9pgimkwo8l6qs2vturi5pyu87tzpyspa
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 9
                - 51
                - 77
                - 103
            "2":
                - 1
                - 9
                - 51
                - 77
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.11.2
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
