_wandb:
    value:
        cli_version: 0.23.1
        e:
            htso8ib9r2kza1t0akapx04bbp17wijr:
                args:
                    - --alpha
                    - "0.1"
                    - --n_epochs
                    - "2"
                    - --batch_size
                    - "100"
                    - --GRASSY_version
                    - AE+REG
                codePath: train_grassy.py
                codePathLocal: train_grassy.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "109951162777600"
                        used: "76480715948032"
                email: stolkowsky@gmail.com
                executable: /sci/labs/orzuk/shaulytolk/GRASSY-Net/molenv/bin/python
                git:
                    commit: 8a0e159ff0a70729f731378bae8d8afa44cb78a7
                    remote: https://github.com/KrishnaswamyLab/GRASSY-Net.git
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-1fec243a-23a1-d1c1-8bf2-9e4aebe5f312
                host: salmon-04
                memory:
                    total: "1623069491200"
                os: Linux-6.12.32-aufs-1-x86_64-with-glibc2.36
                program: /sci/labs/orzuk/shaulytolk/GRASSY-Net/train_grassy.py
                python: CPython 3.11.2
                root: scripts/final_logs/ZINC12K_regress_nokld/
                slurm:
                    cluster_name: moriah
                    conf: /vol/slurm/moriah/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    distribution: cyclic
                    gtids: "0"
                    job_account: orzuk
                    job_cpus_per_node: "4"
                    job_gid: "925"
                    job_id: "43576480"
                    job_name: bash
                    job_nodelist: salmon-04
                    job_num_nodes: "1"
                    job_partition: salmon
                    job_qos: normal
                    job_uid: "212767"
                    job_user: shaulytolk
                    jobid: "43576480"
                    launch_node_ipaddr: 132.65.180.50
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: salmon-04
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "35065"
                    pty_win_col: "133"
                    pty_win_row: "33"
                    srun_comm_host: 132.65.180.50
                    srun_comm_port: "43107"
                    step_gpus: "5"
                    step_id: "0"
                    step_launcher_port: "43107"
                    step_nodelist: salmon-04
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 12316-12317
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /sci/labs/orzuk/shaulytolk/GRASSY-Net
                    submit_host: moriah-gw-02
                    task_pid: "3107396"
                    tasks_per_node: "1"
                    topology_addr: salmon-04
                    topology_addr_pattern: node
                    umask: "0033"
                    working_cluster: moriah:slurmctl-01:6840:9216:109
                startedAt: "2025-12-30T12:26:23.496099Z"
                writerId: htso8ib9r2kza1t0akapx04bbp17wijr
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 9
                - 51
                - 77
                - 103
            "2":
                - 1
                - 9
                - 51
                - 77
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.11.2
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
